<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shiny.Extensions.Push\Shiny.Extensions.Push.csproj" />
    <ProjectReference Include="..\..\src\Shiny.Extensions.Push.Apns\Shiny.Extensions.Push.Apns.csproj" />
    <ProjectReference Include="..\..\src\Shiny.Extensions.Push.Fcm\Shiny.Extensions.Push.Fcm.csproj" />
    <ProjectReference Include="..\..\src\Shiny.Extensions.Push.WebPush\Shiny.Extensions.Push.WebPush.csproj" />
    <ProjectReference Include="..\..\src\Shiny.Extensions.Push.DocumentDb\Shiny.Extensions.Push.DocumentDb.csproj" />
  </ItemGroup>

</Project>
